[tool.poetry]
name = "resinkit-sdk-python"
version = "0.1.0"
description = "A Python SDK for ResinKit"
authors = ["Shijing Lu <resink.ai@yahoo.com>"]
readme = "README.md"
packages = [{ include = "resinkit" }]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^2.0.0"
flink-sql-gateway-api = "1.19.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
isort = "^5.12.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
