[project]
name = "resinkit-sdk-python"
version = "0.1.0"
description = "A Python SDK for ResinKit"
authors = [{ name = "Shijing Lu", email = "resink.ai@yahoo.com" }]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "pandas>=2.0.0,<3",
    "flink-sql-gateway-api==1.19.0",
    "flink-job-manager-api>=1.0.2",
    "panel>=1.7.0",
    "ipywidgets>=8.1.0",
    "notebook>=7.4.2",
]

[dependency-groups]
dev = [
    "pytest>=7.3.1,<8",
    "black>=23.3.0,<24",
    "isort>=5.12.0,<6",
    "flake8>=6.0.0,<7",
]

[tool.hatch.build.targets.sdist]
include = ["resinkit"]

[tool.hatch.build.targets.wheel]
include = ["resinkit"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 120
target-version = ['py37']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
